### ISSUE TITLE
Criar uma rota json no Laravel

### ISSUE THREAD

**Issue by Dovyski** [practice-uffs/practice-api#6]
A ideia dessa issue é criar uma rota prefixada como `/teste/algo` na api. Essa rota deve imprimir um conteúdo json. Para fins de ilustração, podemos imprimir campos da data atual (dia, mês e ano).

Se quiser fazer algo um pouco mais desafiador, pode-se enviar algum dado do aplicativo (usando o objeto do Framework7 que envia/coleta dados de uma API rest).

**Comment by alissonpeloso** [comment]
Consegui realizar o teste 😄

**Comment by CleissonVieira** [comment]
Em reunião todos informaram que entenderam o processo.
